name: Github 3D Profile Contributions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Github 3D Profile
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.SNAKE_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit new data
        uses: stefanzweifel/git-auto-commit-action@v4.15.4
        with:
            commit_message: "✨ Generate & Update Snake Contribution SVG"
            commit_user_name: affan-ch
            commit_user_email: muhammadaffanmaqsood@gmail.com
            commit_author: affan-ch <muhammadaffanmaqsood@gmail.com>
