name: Generate/Update Snake SVG

on:
  schedule:
    # Runs every hour
    - cron: "0 */10 * * *"
  workflow_dispatch:
  

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Generate Snake Game Contributions
        uses: aelassas/snk/svg-only@main
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      - name: Create .ssh directory
        run: |
          mkdir -p $HOME/.ssh
        # The -p flag ensures that the command does not fail if the directory already exists.
  
      - name: Create SSH files
        run: |
          echo "$PRIVATE_SSH_KEY" > $HOME/.ssh/id_ed25519
          echo "$PUBLIC_SSH_KEY" > $HOME/.ssh/id_ed25519.pub
          chmod 600 $HOME/.ssh/id_ed25519 # Set the correct permissions for the private key
          chmod 644 $HOME/.ssh/id_ed25519.pub  # Set the correct permissions for the public key
        env:
          PRIVATE_SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          PUBLIC_SSH_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      
      - name: Commit & Push
        run: |
          git clone git@github.com:affan-ch/affan-ch.git
          echo "Repo Cloned Successfully!"
          rm -f affan-ch/dist/*
          echo "Old Dist Folder Files Removed From Repo Folder"
          echo "<!-- Generated on $(date +"%Y-%m-%d %H:%M:%S") -->" >> dist/github-contribution-grid-snake-dark.svg
          echo "<!-- Generated on $(date +"%Y-%m-%d %H:%M:%S") -->" >> dist/github-contribution-grid-snake.svg
          echo "Added Timestamps comment at the end of SVG files"
          mv dist affan-ch/
          echo "New Dist Folder Files Moved to Repo Folder"
          cd affan-ch
          echo "Inside Repo Folder"
          git config --global user.email "muhammadaffanmaqsood@gmail.com"
          git config --global user.name "affan-ch"
          echo "Set Git Username and Email"
          git add -A .
          echo "Added Changes to Commit"
          git commit -m "Generate & Update Snake Contributions SVG"
          echo "Commit Successful !"
          git push
          echo "Push Successful !"
