name: Generate Snake

on:
  schedule:
    # Runs every 4 hours
    - cron: "0 */4 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Generate Snake Game Contributions
        uses: aelassas/snk/svg-only@main
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      - name: Create .ssh directory
        run: |
          mkdir -p $HOME/.ssh
        # The -p flag ensures that the command does not fail if the directory already exists.
  
      - name: Create SSH files
        run: |
          echo "$PRIVATE_SSH_KEY" > $HOME/.ssh/id_ed25519
          echo "$PUBLIC_SSH_KEY" > $HOME/.ssh/id_ed25519.pub
          chmod 600 $HOME/.ssh/id_ed25519 # Set the correct permissions for the private key
          chmod 644 $HOME/.ssh/id_ed25519.pub  # Set the correct permissions for the public key
        env:
          PRIVATE_SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          PUBLIC_SSH_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      
      - name: Commit & Push
        run: |
          git clone git@github.com:affan-ch/affan-ch.git
          mv dist affan-ch/
          cd affan-ch
          git config --global user.email "muhammadaffanmaqsood@gmail.com"
          git config --global user.name "affan-ch"
          git add -A .
          git commit -m "Generate & Update Snake Contributions SVG"
          git push
